name: Sugerir uma melhoria
description: Sugira uma funcionalidade ou melhoria para o Ludryn.
title: "[Sugestão] "
labels:
  - enhancement
body:
  - type: textarea
    id: idea
    attributes:
      label: Qual é a sua ideia?
      description: Explique o que gostaria de adicionar ou modificar.
    validations:
      required: true
  - type: textarea
    id: benefit
    attributes:
      label: Como isso ajudaria?
    validations:
      required: true
